name: Windows Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-python
            mingw-w64-x86_64-python-pillow
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-shaderc
            mingw-w64-x86_64-vulkan-headers
            mingw-w64-x86_64-vulkan-loader
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-glew
            mingw-w64-x86_64-cglm
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL_mixer
          update: true

    - name: Convert github.workspace to mingw path
      shell: msys2 {0}
      run: echo "MINGW_WORKSPACE=$(cygpath -u '${{github.workspace}}')" >> $GITHUB_ENV

    - name: Configure CMake
      shell: msys2 {0}
      run: cmake -B "$MINGW_WORKSPACE/build" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      shell: msys2 {0}
      run: cmake --build "$MINGW_WORKSPACE/build" --config ${{env.BUILD_TYPE}}

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: game.windows
        path: |
          build/game.exe
          build/SDL2.dll
          build/SDL2_mixer.dll
          build/glew32.dll
          build/zlib1.dll
          build/libmpg123-0.dll
          build/libFLAC.dll
          build/libopusfile-0.dll
          build/libvorbisfile-3.dll
          build/libwavpack-1.dll
          build/libxmp.dll
          build/libvorbis-0.dll
          build/libogg-0.dll
          build/libwinpthread-1.dll
          build/libopus-0.dll 
          build/assets/
        retention-days: 90
